#include <stdio.h>
#include "holberton.h"
int main(void)
{
	int len, len2;
	printf("==========================\n");
	printf("==========================\n");
	printf("         DECIMAL          \n");
	printf("==========================\n");
	printf("Expected:  %d\n", 6);
	_printf("Actual :   %d\n", 6);
	printf("Expected:  %d\n", 1998);
	_printf("Actual :   %d\n", 1998);
	printf("Expected:  %d\n", -1998);
	_printf("Actual :   %d\n", -1998);
	printf("Expected:  %d\n", 0);
	_printf("Actual :   %d\n", 0);
	len = printf("%d\n");
	len2 = _printf("%d\n");
	printf("Expected:  %d\n", (len - 1));
	_printf("Actual :   %d\n", (len2 - 1));
	len = printf("%d - %d\n", "Elkin", "Mejia");
	len2 = _printf("%d - %d\n", "Elkin", "Mejia");
	printf("Expected: %d%%\n", 4);
	_printf("Actual :   %d%%\n", 4);
	printf("Expected: %%%d\n", 4);
	_printf("Actual :   %%%d\n", 4);
	printf("Expected: %V%d\n", 4);
	_printf("Actual :   %V%d\n", 4);
	len = printf("Expected:  %d\n", NULL);
	len2 = _printf("Actual :   %d\n", NULL);
	printf("Expected:  %i\n", len);
	_printf("Actual :  %i\n", len2);
	printf("Expected:  %d\n", -0);
	_printf("Actual :   %d\n", -0);
	printf("Expected:  %d\n", 6.7);
	_printf("Actual :   %d\n", 6.7);
	printf("Expected:  %d\n", 'H');
	_printf("Actual :   %d\n", 'H');
	printf("Expected:  %d\n", 00000100);
	_printf("Actual :   %d\n", 00000100);
	printf("==========================\n");
	printf("==========================\n");
	printf("        INTEGER           \n");
	printf("==========================\n");
	printf("Expected:  %i\n", NULL);
	_printf("Actual :   %i\n", NULL);
	printf("Expected:  %i\n", 6);
	_printf("Actual :   %i\n", 6);
	printf("Expected:  %i\n", 1998);
	_printf("Actual :   %i\n", 1998);
	printf("Expected:  %i\n", -1998);
	_printf("Actual :   %i\n", -1998);
	printf("Expected:  %i\n", 0);
	_printf("Actual :   %i\n", 0);
	printf("Expected:  %i\n", -0);
	_printf("Actual :   %i\n", -0);
	printf("Expected:  %i\n", 6.7);
	_printf("Actual :   %i\n", 6.7);
	printf("Expected:  %i\n", 'H');
	_printf("Actual :   %i\n", 'H');
	printf("Expected:  %i\n", 0xF);
	_printf("Actual :   %i\n", 0xF);
	printf("Expected:  %i\n", 0xE);
	_printf("Actual :   %i\n", 0xE);
	printf("Expected:  %i\n", 0x7);
	_printf("Actual :   %i\n", 0x7);
	printf("Expected:  %i\n", 00000000);
	_printf("Actual :   %i\n", 00000000);
	printf("Expected:  %i\n", 00000001);
	_printf("Actual :   %i\n", 00000001);
	printf("Expected:  %i\n", 00000100);
	_printf("Actual :   %i\n", 00000100);
	len = printf("%", 00000100);
	len2 = _printf("%", 00000100);
	printf("Expected:  %i\n", len);
	_printf("Actual :   %i\n", len2);
	printf("==========================\n");
	return (0);
}
